run-1:
	go run main.go --helloPort 7780 --helloName Alan

run-2:
	go run main.go --helloPort 7781 --helloName Bas

run-3:
	go run main.go --helloPort 7782 --helloName Ciri

run-4:
	go run main.go --helloPort 7783 --helloName David

run-5:
	go run main.go --helloPort 7784 --helloName Emily
